import {
  NewsItem,
  TradeSetup,
  RankingItem,
  AdviceBlock,
  CategoryComparison,
  MarketSummary,
  BitcoinMarket,
  EveningBriefItem,
  DailySummary,
  AssetPrice,
} from './types';

// ─── Timestamps (fixed ISO strings — prevents SSR/client hydration mismatch) ──
// These are intentionally static mock timestamps anchored to 2026-03-13.
// Relative labels ("15 min geleden") are computed via getMockRelativeTime() in
// FreshnessLabel/NewsCard, which uses MOCK_REFERENCE_NOW as the reference point
// so ages stay correct regardless of the actual visit time.

export const MOCK_REFERENCE_NOW = '2026-03-13T15:00:00.000Z';

const NOW       = '2026-03-13T15:00:00.000Z';
const MINUS_15M = '2026-03-13T14:45:00.000Z';
const MINUS_1H  = '2026-03-13T14:00:00.000Z';
const MINUS_2H  = '2026-03-13T13:00:00.000Z';
const MINUS_3H  = '2026-03-13T12:00:00.000Z';
const MINUS_4H  = '2026-03-13T11:00:00.000Z';
const MINUS_6H  = '2026-03-13T09:00:00.000Z';
const MINUS_8H  = '2026-03-13T07:00:00.000Z';
const MINUS_12H = '2026-03-13T03:00:00.000Z';

// ─── Index Prices ─────────────────────────────────────────────────────────────

export const indexPrices: AssetPrice[] = [
  {
    ticker: 'SPX',
    name: 'S&P 500',
    category: 'etf',
    price: 5180,
    currency: 'EUR',
    changePercent: -0.52,
    changeAbsolute: -26.94,
    dataStatus: 'vertraagd',
    lastUpdated: MINUS_15M,
  },
  {
    ticker: 'NDX',
    name: 'Nasdaq 100',
    category: 'etf',
    price: 18224,
    currency: 'EUR',
    changePercent: -0.88,
    changeAbsolute: -161.17,
    dataStatus: 'vertraagd',
    lastUpdated: MINUS_15M,
  },
  {
    ticker: 'DAX',
    name: 'DAX 40',
    category: 'etf',
    price: 23641.55,
    currency: 'EUR',
    changePercent: 0.22,
    changeAbsolute: 51.41,
    dataStatus: 'vertraagd',
    lastUpdated: MINUS_15M,
  },
  {
    ticker: 'BTC',
    name: 'Bitcoin',
    category: 'bitcoin',
    price: 62696,
    currency: 'EUR',
    changePercent: -1.87,
    changeAbsolute: -1196,
    dataStatus: 'vertraagd',
    lastUpdated: MINUS_15M,
  },
];

// ─── Market Summary ───────────────────────────────────────────────────────────

export const marketSummary: MarketSummary = {
  regime: 'volatile',
  regimeLabel: 'Verhoogde volatiliteit',
  topSignal: 'Tech-correctie zet door — Nasdaq -3,4% in 5 dagen. Rotatie naar waarde-aandelen zichtbaar.',
  biggestRisk: 'Fed houdt rente ongewijzigd. CPI-data morgen kan verdere correctie veroorzaken.',
  whatToWatchNext: 'CPI-data morgen 14:30 NL-tijd. SPX €5.180 als sleutelsteun. Bitcoin €61k steunzone.',
  sentiment: 'bearish',
  lastUpdated: MINUS_15M,
  dataStatus: 'vertraagd',
  indexPrices,
};

// ─── News Items ───────────────────────────────────────────────────────────────

export const allNewsItems: NewsItem[] = [
  {
    id: 'news-001',
    timestamp: MINUS_1H,
    source: 'Reuters',
    headline: 'Fed-functionaris: inflatie blijft boven doelstelling, meer geduld vereist',
    summary:
      'Een invloedrijke Fed-gouverneur benadrukte dat de inflatie nog niet voldoende daalt richting de 2%-doelstelling. Hij liet doorschemeren dat renteverlagingen pas later in 2025 realistisch zijn dan de markt momenteel inprijst.',
    categoryTags: ['macro', 'rente', 'fed'],
    assetTags: ['SPX', 'NDX', 'BTC'],
    relevanceScore: 9.2,
    marketImpactScore: 8.7,
    sentiment: 'bearish',
    timeHorizon: 'swing',
    isRelevant: true,
    whyItMatters:
      'Hogere rentes langer aanhouden drukt groeiaandelen en risicovolle assets zoals Bitcoin. Dit past in het patroon van de afgelopen weken waarbij tech-aandelen onder druk staan. Het herpositioneert verwachtingen voor Q2 2025.',
    affectedCategories: ['aandeel', 'etf', 'bitcoin'],
    affectedInstruments: ['SPX', 'QQQ', 'BTC', 'AAPL', 'NVDA'],
    scenarioImplication:
      'Bearish voor groeiaandelen en Bitcoin op korte termijn. Neutraal tot licht positief voor value-ETFs en dividend-aandelen.',
    eventType: 'macro',
    watchNext: 'CPI-data morgen en Fed-vergadering agenda. Reactie van 10-jaars Treasury yield.',
    invalidationNote: 'Ongeldig als volgende CPI-data sterk meevalt (< 2,8%).',
  },
  {
    id: 'news-002',
    timestamp: MINUS_2H,
    source: 'Bloomberg',
    headline: 'NVIDIA Q4-resultaten overtreffen verwachtingen — datacenter-omzet +142% j-o-j',
    summary:
      'NVIDIA rapporteerde een kwartaalomzet van $39,3 miljard, ruim boven de consensus van $38,2 miljard. Datacenter-segment groeide met 142% jaar-op-jaar. Management verhoogde guidance voor Q1 2025.',
    categoryTags: ['earnings', 'tech', 'ai'],
    assetTags: ['NVDA', 'SMH', 'QQQ'],
    relevanceScore: 8.8,
    marketImpactScore: 7.9,
    sentiment: 'bullish',
    timeHorizon: 'swing',
    isRelevant: true,
    whyItMatters:
      'NVIDIA is barometer voor AI-investeringscyclus en tech-sentiment. Sterke resultaten reduceren downside-risico voor Nasdaq en AI-gerelateerde ETFs op middellange termijn. Maar: markt had dit deels ingeprijsd — koersreactie kan beperkt zijn.',
    affectedCategories: ['aandeel', 'etf'],
    affectedInstruments: ['NVDA', 'QQQ', 'SMH', 'SOXX'],
    scenarioImplication: 'Positief voor tech-ETFs en semiconductor-aandelen. Korte termijn rebound mogelijk.',
    eventType: 'earnings',
    watchNext: 'Pre-market koers NVDA. Reactie van sectorgenoten AMD, INTC, ASML.',
    invalidationNote: 'Ongeldig als guidance in Q&A naar beneden bijgesteld wordt.',
  },
  {
    id: 'news-003',
    timestamp: MINUS_3H,
    source: 'CoinDesk',
    headline: 'Bitcoin ETF-uitstroom bereikt hoogste niveau in 6 weken — €442M uitgestroomd',
    summary:
      'De spot Bitcoin ETFs zagen gezamenlijk €442 miljoen aan uitstroom, het grootste dagbedrag in zes weken. BlackRock IBIT bleef positief maar Fidelity en Ark rapporteerden significante uitstroom.',
    categoryTags: ['bitcoin', 'etf', 'flows'],
    assetTags: ['BTC', 'IBIT', 'FBTC'],
    relevanceScore: 9.0,
    marketImpactScore: 8.3,
    sentiment: 'bearish',
    timeHorizon: 'volgende-sessie',
    isRelevant: true,
    whyItMatters:
      'ETF-uitstroom is directe indicator van institutionele vraag. Bij aanhoudende uitstroom ontstaat verkoopdruk. €60k–€62k is de kritieke steunzone. Doorbrekken daarvan opent weg naar €54k–€57k.',
    affectedCategories: ['bitcoin'],
    affectedInstruments: ['BTC', 'IBIT', 'FBTC', 'ARKB'],
    scenarioImplication: 'Bearish druk op Bitcoin tot steunzone getest of sentiment keert.',
    eventType: 'bitcoin',
    watchNext: 'Dagelijkse ETF-stroomdata. Bitcoin dominance indicator. Whale wallet movements.',
    invalidationNote: 'Ongeldig als morgen instroom van >€276M gerapporteerd wordt.',
  },
  {
    id: 'news-004',
    timestamp: MINUS_4H,
    source: 'Financial Times',
    headline: 'EU kondigt nieuwe kapitaalvereisten aan voor Europese banken — impact op kredietverlening',
    summary:
      'De Europese Bankautoriteit kondigde strengere kapitaalvereisten aan die per 2026 ingaan. Analisten verwachten dat dit de kredietverlening beperkt maar de sectorstabiliteit vergroot.',
    categoryTags: ['macro', 'europa', 'banken', 'regelgeving'],
    assetTags: ['EWG', 'FEZ', 'ING', 'ABN'],
    relevanceScore: 6.4,
    marketImpactScore: 5.2,
    sentiment: 'neutraal',
    timeHorizon: 'lange-termijn',
    isRelevant: false,
    affectedCategories: ['aandeel', 'etf'],
    affectedInstruments: ['ING', 'ABN', 'FEZ', 'EWG'],
    eventType: 'regelgeving',
  },
  {
    id: 'news-005',
    timestamp: MINUS_6H,
    source: 'WSJ',
    headline: 'Apple ontwikkelt eigen AI-chip voor datacenters — afname afhankelijkheid van NVIDIA',
    summary:
      'Apple is naar verluidt bezig met een geavanceerde AI-inferentie chip voor gebruik in eigen datacenters. Dit zou de afhankelijkheid van NVIDIA GPU\'s verminderen en de cloud-AI-capabilities van Apple uitbreiden.',
    categoryTags: ['tech', 'ai', 'semis'],
    assetTags: ['AAPL', 'NVDA', 'QQQ'],
    relevanceScore: 7.5,
    marketImpactScore: 6.8,
    sentiment: 'bullish',
    timeHorizon: 'lange-termijn',
    isRelevant: true,
    whyItMatters:
      'Strategisch bullish voor Apple op lange termijn. Neutraal tot licht negatief voor NVIDIA op erg lange termijn. Op korte termijn geen directe koersimpact verwacht — dit is meerjarige ontwikkeling.',
    affectedCategories: ['aandeel', 'etf'],
    affectedInstruments: ['AAPL', 'NVDA', 'QQQ'],
    scenarioImplication: 'Lange termijn positief voor Apple. Beperkte directe marktimpact.',
    eventType: 'technisch',
    watchNext: 'Apple WWDC aankondigingen. AI-capex guidance in volgende earnings.',
  },
  {
    id: 'news-006',
    timestamp: MINUS_8H,
    source: 'CoinTelegraph',
    headline: 'El Salvador verhoogt Bitcoin-reserve naar 6.000 BTC ondanks IMF-druk',
    summary:
      'El Salvador heeft zijn nationale Bitcoin-reserve uitgebreid met 200 BTC, ondanks lopende onderhandelingen met het IMF over een leningsprogramma. President Bukele bevestigde de aankopen via officieel kanaal.',
    categoryTags: ['bitcoin', 'macro', 'geopolitiek'],
    assetTags: ['BTC'],
    relevanceScore: 6.9,
    marketImpactScore: 4.5,
    sentiment: 'bullish',
    timeHorizon: 'lange-termijn',
    isRelevant: false,
    affectedCategories: ['bitcoin'],
    affectedInstruments: ['BTC'],
    eventType: 'geopolitiek',
  },
  {
    id: 'news-007',
    timestamp: MINUS_12H,
    source: 'CNBC',
    headline: 'S&P 500 correctie van 5% historisch normaal in bull markt — analisten zien koopkans',
    summary:
      'Diverse sell-side analisten stellen dat de huidige correctie van ca. 5% van het hoogste punt binnen historische normen valt voor een aanhoudende bull markt. JPMorgan houdt jaareinde-doel van 6.500 op SPX.',
    categoryTags: ['macro', 'analyse', 'spx'],
    assetTags: ['SPX', 'QQQ', 'VOO'],
    relevanceScore: 5.5,
    marketImpactScore: 3.8,
    sentiment: 'bullish',
    timeHorizon: 'lange-termijn',
    isRelevant: false,
    affectedCategories: ['etf', 'aandeel'],
    eventType: 'algemeen',
  },
  {
    id: 'news-008',
    timestamp: MINUS_3H,
    source: 'Reuters',
    headline: 'Microsoft Azure omzetgroei vertraagt iets — maar AI-diensten compenseren',
    summary:
      'Microsoft Azure groeide met 31% in het afgelopen kwartaal, licht onder de 33% die analisten verwachtten. AI-diensten (Copilot, OpenAI-producten) groeiden met 157% maar zijn nog beperkt in absolute omzetbijdrage.',
    categoryTags: ['earnings', 'tech', 'cloud', 'ai'],
    assetTags: ['MSFT', 'QQQ'],
    relevanceScore: 7.8,
    marketImpactScore: 7.2,
    sentiment: 'neutraal',
    timeHorizon: 'swing',
    isRelevant: true,
    whyItMatters:
      'Cloud-groeivertraging bevestigt dat de AI-kapex-cyclus nog niet volledig vertaalt naar omzetgroei. Belangrijk signaal voor het gehele cloud/AI-segment. Neutraal voor korte termijn maar stelt vragen bij waarderingen van AI-aandelen.',
    affectedCategories: ['aandeel', 'etf'],
    affectedInstruments: ['MSFT', 'AMZN', 'GOOGL', 'QQQ'],
    scenarioImplication: 'Druk op hoge AI-waarderingen in bredere tech-sector.',
    eventType: 'earnings',
    watchNext: 'Amazon AWS en Google Cloud resultaten. Azure-groeitrend in Q2.',
  },
  {
    id: 'news-009',
    timestamp: MINUS_2H,
    source: 'Bloomberg',
    headline: 'Bitcoin on-chain data: lange-termijn houders verkopen nog niet — HODL-waves stabiel',
    summary:
      'On-chain analyses tonen dat adressen met BTC ouder dan 6 maanden hun positie nauwelijks wijzigen. Short-term holders zijn verantwoordelijk voor het meeste verkoopvolume. Historisch positief signaal voor medium-term outlook.',
    categoryTags: ['bitcoin', 'on-chain', 'analyse'],
    assetTags: ['BTC'],
    relevanceScore: 7.4,
    marketImpactScore: 5.8,
    sentiment: 'bullish',
    timeHorizon: 'swing',
    isRelevant: true,
    whyItMatters:
      'Lange-termijn houders (LTH) zijn de sterkste indicatoren van markt-overtuiging. LTH-stabiliteit suggereert dat de huidige correctie door zwakke handen gedreven wordt, niet door structurele exit. Historisch volgt na dergelijke fasen een hervatting van de opwaartse trend.',
    affectedCategories: ['bitcoin'],
    affectedInstruments: ['BTC'],
    scenarioImplication: 'Medium-term bullish, maar short-term druk houdt mogelijk aan.',
    eventType: 'bitcoin',
    watchNext: 'NUPL (Net Unrealized Profit/Loss) indicator. Short-term holder realized price (~€61k).',
    invalidationNote: 'Ongeldig als LTH-spending rate significant stijgt (> 0,5% per dag).',
  },
  {
    id: 'news-010',
    timestamp: MINUS_1H,
    source: 'MarketWatch',
    headline: 'VIX-index stijgt naar 24 — verhoogde onzekerheid voor komende 30 dagen',
    summary:
      'De CBOE Volatility Index noteerde op 24, het hoogste niveau in acht weken. Optiemarkt prijst in dat grotere koersuitslagen verwacht worden voor de S&P 500 in de komende maand.',
    categoryTags: ['macro', 'volatiliteit', 'opties'],
    assetTags: ['VIX', 'SPX'],
    relevanceScore: 8.1,
    marketImpactScore: 7.5,
    sentiment: 'bearish',
    timeHorizon: 'volgende-sessie',
    isRelevant: true,
    whyItMatters:
      'VIX boven 20 wijst op verhoogd risico. Bij VIX >25 vergroot kans op verdere sell-off. Voor day traders: hogere spreads en snellere koersuitslagen. Voor maandbeleggers: beperkte actie, mogelijke koopkans bij verdere daling.',
    affectedCategories: ['aandeel', 'etf'],
    affectedInstruments: ['SPX', 'QQQ', 'VOO'],
    scenarioImplication: 'Verhoogde volatiliteit — selectiviteit vereist voor daghandel.',
    eventType: 'macro',
    watchNext: 'VIX-trend komende 2 dagen. Put/call ratio. Opties-expiratiedata.',
  },
];

export const relevantNewsItems = allNewsItems.filter((n) => n.isRelevant);

// ─── Trade Setups ─────────────────────────────────────────────────────────────

export const tradeSetups: TradeSetup[] = [
  {
    id: 'setup-001',
    ticker: 'NVDA',
    name: 'NVIDIA Corporation',
    category: 'aandeel',
    direction: 'long',
    setupType: 'Post-earnings momentum + steunniveau',
    currentPrice: '€818',
    entryZone: '€806–€821',
    stopLoss: '€790',
    target1: '€860',
    target2: '€893',
    riskReward: 2.4,
    confidenceScore: 7.2,
    catalyst: 'Sterk kwartaalrapport + datacenter-guidance verhoogd',
    volumeContext: 'Volume 2,3x boven 20-daags gemiddelde na earnings',
    invalidationCondition: 'Sluit onder €790 op dagbasis',
    tradeabilityState: 'bevestiging-nodig',
    lastUpdated: MINUS_15M,
    sessionRelevance: ['open', 'pre-market'],
    notes: 'Pre-market gap suggereert sterke open. Wacht op consolidatie boven €806 voor entry.',
  },
  {
    id: 'setup-002',
    ticker: 'QQQ',
    name: 'Invesco Nasdaq 100 ETF',
    category: 'etf',
    direction: 'long',
    setupType: 'Oversold rebound — steunzone test',
    currentPrice: '€437',
    entryZone: '€432–€439',
    stopLoss: '€425',
    target1: '€453',
    target2: '€462',
    riskReward: 2.0,
    confidenceScore: 6.1,
    catalyst: 'Oversold RSI (<35) op dagchart + steun bij 200-daags MA',
    volumeContext: 'Volume in lijn met gemiddelde — geen paniekverkoop',
    invalidationCondition: 'Sluit onder €425 op dagbasis',
    tradeabilityState: 'bevestiging-nodig',
    lastUpdated: MINUS_15M,
    sessionRelevance: ['open'],
    notes: 'Fed-risico aanwezig. Positiegrootte beperken. Hogere kans op setup als VIX onder 22 daalt.',
  },
  {
    id: 'setup-003',
    ticker: 'BTC',
    name: 'Bitcoin',
    category: 'bitcoin',
    direction: 'long',
    setupType: 'Steunzone retest — short-term bounce',
    currentPrice: '€62.700',
    entryZone: '€60.500–€62.000',
    stopLoss: '€58.500',
    target1: '€67.000',
    target2: '€72.000',
    riskReward: 2.3,
    confidenceScore: 6.5,
    catalyst: 'Steunzone €60k–€62k + LTH-stabiliteit on-chain',
    volumeContext: 'Spot-volume dalende — short-term holders verkopen, LTH houdt',
    invalidationCondition: 'Dagelijkse sluit onder €58.000',
    tradeabilityState: 'bevestiging-nodig',
    lastUpdated: MINUS_15M,
    sessionRelevance: ['open', 'after-hours', 'pre-market'],
    notes: 'ETF-uitstroom vormt tegenwind. Wacht op reversal-candle of volume-bevestiging.',
  },
  {
    id: 'setup-004',
    ticker: 'AAPL',
    name: 'Apple Inc.',
    category: 'aandeel',
    direction: 'long',
    setupType: 'AI-chip nieuws katalysator + steunniveau',
    currentPrice: '€204',
    entryZone: '€200–€206',
    stopLoss: '€194',
    target1: '€215',
    target2: '€224',
    riskReward: 2.3,
    confidenceScore: 5.8,
    catalyst: 'Eigen AI-chip ontwikkeling — structurele margedrijver op LT',
    volumeContext: 'Normaal volume, geen bijzondere activiteit',
    invalidationCondition: 'Sluit onder €194',
    tradeabilityState: 'alleen-observeren',
    lastUpdated: MINUS_1H,
    sessionRelevance: ['open'],
    notes: 'Eerder in watchlist dan actieve setup. Geen directe katalysator voor vandaag.',
  },
  {
    id: 'setup-005',
    ticker: 'SPY',
    name: 'SPDR S&P 500 ETF',
    category: 'etf',
    direction: 'short',
    setupType: 'Correctie — bearish momentum',
    currentPrice: '€511',
    entryZone: '€514–€519',
    stopLoss: '€525',
    target1: '€500',
    target2: '€491',
    riskReward: 1.8,
    confidenceScore: 5.2,
    catalyst: 'Fed-hawkishness + VIX stijging + tech-zwakte',
    volumeContext: 'Verhoogd volume bij dalingen — distributiepatroon',
    invalidationCondition: 'Sluit boven €525',
    tradeabilityState: 'vermijden',
    lastUpdated: MINUS_1H,
    sessionRelevance: ['open'],
    notes: 'CPI-data morgen maakt shorting riskant. Vermijden tot data bekend is.',
  },
];

// ─── Monthly Rankings ─────────────────────────────────────────────────────────

export const monthlyStockRankings: RankingItem[] = [
  {
    rank: 1,
    ticker: 'NVDA',
    name: 'NVIDIA Corporation',
    category: 'aandeel',
    score: 8.7,
    changePercent: 1.8,
    rationale: 'Sterke earnings, AI-datacenter leiderschap, guidance verhoogd. Correctie biedt koopmogelijkheid voor maandelijkse accumulation.',
    mainDrivers: ['AI-datacenter groei +142%', 'Verhoogde guidance Q1', 'Dominante marktpositie GPUs'],
    risks: 'Hoge waardering (P/E >60), afhankelijkheid van datacenter-capex-cyclus, geopolitieke chips-restricties.',
    timeHorizon: 'lange-termijn',
    tradeabilityState: 'bevestiging-nodig',
    sentiment: 'bullish',
    monthlyAllocationSuitable: true,
  },
  {
    rank: 2,
    ticker: 'MSFT',
    name: 'Microsoft Corporation',
    category: 'aandeel',
    score: 8.1,
    changePercent: -0.4,
    rationale: 'Solide cloud + AI-positionering. Lagere volatiliteit dan pure-play AI. Azure-vertraging is korte-termijn zorg, geen structureel probleem.',
    mainDrivers: ['Azure cloud dominantie', 'OpenAI-integratie Copilot', 'Sterk dividend + buybacks'],
    risks: 'Cloud-groeivertraging, regulatoire druk, hoge waardering.',
    timeHorizon: 'lange-termijn',
    tradeabilityState: 'actionable',
    sentiment: 'bullish',
    monthlyAllocationSuitable: true,
  },
  {
    rank: 3,
    ticker: 'AAPL',
    name: 'Apple Inc.',
    category: 'aandeel',
    score: 7.4,
    changePercent: 0.2,
    rationale: 'Stabiele cashflow, eigen AI-chip ontwikkeling positief voor LT-marge. Minder hype, meer structureel.',
    mainDrivers: ['Eigen AI-chip datacenter', 'Services-segment groei', 'Sterk ecosystem'],
    risks: 'China-exposure, iPhone-marktaandeel druk, AI-adoptievertraging.',
    timeHorizon: 'lange-termijn',
    tradeabilityState: 'actionable',
    sentiment: 'neutraal',
    monthlyAllocationSuitable: true,
  },
  {
    rank: 4,
    ticker: 'META',
    name: 'Meta Platforms',
    category: 'aandeel',
    score: 7.0,
    changePercent: -1.1,
    rationale: 'Sterke advertentie-engine + Reality Labs uitleg verwacht. AI-advertentietargeting verbetert marges.',
    mainDrivers: ['AI-advertentie-targeting', 'Instagram + WhatsApp monetisatie', 'Cost-discipline'],
    risks: 'Capex Reality Labs, regulatoire risicos EU, afhankelijkheid advertentiemarkt.',
    timeHorizon: 'lange-termijn',
    tradeabilityState: 'alleen-observeren',
    sentiment: 'neutraal',
    monthlyAllocationSuitable: true,
  },
];

export const monthlyETFRankings: RankingItem[] = [
  {
    rank: 1,
    ticker: 'QQQ',
    name: 'Invesco Nasdaq 100 ETF',
    category: 'etf',
    score: 8.3,
    changePercent: -0.7,
    rationale: 'Diversificatie over top 100 Nasdaq-bedrijven. Correctie brengt betere instapprijs. Ideaal voor maandelijkse accumulation.',
    mainDrivers: ['Brede tech-diversificatie', 'AI-zwaargewichten in index', 'Langjarige outperformance'],
    risks: 'Tech-concentratie, rentegevoeligheid, correctie-risico bij Fed-hawkishness.',
    timeHorizon: 'lange-termijn',
    tradeabilityState: 'actionable',
    sentiment: 'bullish',
    monthlyAllocationSuitable: true,
  },
  {
    rank: 2,
    ticker: 'VOO',
    name: 'Vanguard S&P 500 ETF',
    category: 'etf',
    score: 7.9,
    changePercent: -0.4,
    rationale: 'Laagste kosten S&P 500 blootstelling. Kerndeel van elke portefeuille. Defensiever dan QQQ.',
    mainDrivers: ['Brede marktblootstelling', 'Ultralage kosten (0.03%)', 'Gediversifieerd risico'],
    risks: 'Marktcorrectie-risico, rente-gevoeligheid, beperkte outperformance vs. index.',
    timeHorizon: 'lange-termijn',
    tradeabilityState: 'actionable',
    sentiment: 'neutraal',
    monthlyAllocationSuitable: true,
  },
  {
    rank: 3,
    ticker: 'SOXX',
    name: 'iShares Semiconductor ETF',
    category: 'etf',
    score: 7.1,
    changePercent: 0.9,
    rationale: 'Gerichte blootstelling aan semiconductor-cyclus. Hogere volatiliteit, hoger potentieel op LT.',
    mainDrivers: ['AI-chip-supercycle', 'TSMC + NVDA dominantie', 'Defensie-elektronica groei'],
    risks: 'Cyclisch, geopolitieke restricties, hogere volatiliteit.',
    timeHorizon: 'lange-termijn',
    tradeabilityState: 'bevestiging-nodig',
    sentiment: 'bullish',
    monthlyAllocationSuitable: true,
  },
  {
    rank: 4,
    ticker: 'VIG',
    name: 'Vanguard Dividend Appreciation ETF',
    category: 'etf',
    score: 6.5,
    changePercent: 0.1,
    rationale: 'Defensieve positionering voor tijden van verhoogde marktvolatiliteit. Dividendgroei als buffer.',
    mainDrivers: ['Dividendgroei-focus', 'Lagere volatiliteit', 'Defensief in correcties'],
    risks: 'Underperformance in bull markten, beperkte groeicomponent.',
    timeHorizon: 'lange-termijn',
    tradeabilityState: 'actionable',
    sentiment: 'neutraal',
    monthlyAllocationSuitable: true,
  },
];

// ─── Category Comparison ──────────────────────────────────────────────────────

export const monthlyCategoryComparison: CategoryComparison = {
  winner: 'etf',
  rationale:
    'ETFs bieden in het huidige volatiele regime de beste risico-rendement-verhouding voor maandelijkse allocatie. Aandelen zijn kansrijker maar vereisen meer selectiviteit. Bitcoin is interessant maar verhoogde uitstroom en macro-tegenwind reduceren de aantrekkelijkheid tijdelijk.',
  scores: {
    aandelen: 7.2,
    etfs: 8.0,
    bitcoin: 6.1,
  },
  sampleAllocation: {
    aandelen: 35,
    etfs: 45,
    bitcoin: 10,
    cash: 10,
  },
  avoidThisMonth: [
    'Hoge leverage in tech-posities',
    'Speculatieve small-caps zonder fundamentele basis',
    'Altcoins en speculatieve crypto',
    'Concentratie in één sector (>40% in tech)',
  ],
  lastUpdated: MINUS_2H,
};

// ─── Advice Blocks ─────────────────────────────────────────────────────────────

export const monthlyAdvice: AdviceBlock = {
  title: 'Advies voor deze maand',
  subtitle: 'Maandelijkse allocatie — maart 2026',
  summary:
    'De markt bevindt zich in een correctiefase na sterke prestaties eerder dit jaar. VIX boven 20 en Fed-hawkishness creëren verhoogde onzekerheid. Dit is geen paniek, maar selectiviteit is vereist. ETFs verdienen de voorkeur boven losse aandelen voor de kernpositie. NVDA en MSFT zijn de meest kansrijke losse aandelen. Bitcoin is tijdelijk minder aantrekkelijk door ETF-uitstroom maar fundamentals op lange termijn intact.',
  mainDrivers: [
    'Fed-hawkishness: renteverlagingen uitgesteld',
    'Tech-correctie biedt gedeeltelijk koopkans (NVDA, MSFT)',
    'Bitcoin ETF-uitstroom — short-term negatief druk',
    'DAX relatief sterk — Europese blootstelling interessant',
    'VIX >20 — verhoogde volatiliteit vraagt discipline',
  ],
  risks: [
    'CPI-data morgen kan verdere correctie veroorzaken',
    'Fed harder-dan-verwacht bij volgende vergadering',
    'Geopolitieke escalatie (Oost-Europa, Taiwan)',
    'Creditmarkten tonen stress bij hogere rentes',
  ],
  counterArguments: [
    'Correctie van 5% is historisch normaal in bull markt',
    'Earnings-seizoen is overwegend positief',
    'Balansposities bij grote bedrijven zijn sterk',
    'LTH Bitcoin-houders verkopen niet — structureel intact',
  ],
  scenarios: {
    bullish: {
      label: 'Bullish scenario',
      description: 'CPI morgen valt mee, Fed-toon verzacht.',
      probability: 'gemiddeld',
      implication: 'Nasdaq herstelt 3–5%. Bitcoin keert terug boven €65k. Full allocatie gerechtvaardigd.',
      watchTriggers: ['CPI < 2,9%', 'Fed-functionaris zachter taalgebruik', 'VIX onder 20'],
      invalidation: 'Ongeldig als CPI hoger dan 3,2%',
    },
    bearish: {
      label: 'Bearish scenario',
      description: 'CPI hoger dan verwacht, verdere correctie.',
      probability: 'gemiddeld',
      implication: 'SPX test €4.700. Nasdaq -8% mogelijk. Bitcoin test €55k. Wacht met grotere posities.',
      watchTriggers: ['CPI > 3,2%', 'VIX boven 28', 'Creditmarkt stress'],
      invalidation: 'Ongeldig als Fed hint op mogelijke verlaging',
    },
    neutral: {
      label: 'Neutraal scenario',
      description: 'Markten bewegen zijwaarts, onzekerheid duurt aan.',
      probability: 'hoog',
      implication: 'Systematische DCA in kwaliteitsposities. Geen grote moves. Geduld vereist.',
      watchTriggers: ['VIX stabiel 20–24', 'SPX tussen €4.800–€5.000'],
    },
  },
  conclusion:
    'Systematische allocatie naar kernposities (VOO, QQQ) is verstandig. Losse aandelen alleen via bijkopen in bestaande posities (NVDA, MSFT). Bitcoin beperkte allocatie (max 10%) — hogere risicotolerantie vereist. Wacht met nieuwe speculatieve posities tot marktregime duidelijker is.',
  actionPoints: [
    'Maandelijkse DCA in VOO en/of QQQ uitvoeren',
    'NVDA bijkopen bij bevestiging boven €806',
    'MSFT toevoegen als onderdeel van kern-tech-positie',
    'Bitcoin allocatie beperken tot max 10% van inleg deze maand',
    'CPI-data afwachten voor grote beslissingen',
  ],
  whatToAvoid: [
    'Nieuwe speculatieve posities voor CPI-data',
    'Verhoogde leverage in volatiele markt',
    'Concentratie boven 40% in één sector',
    'Altcoins of speculatieve crypto',
  ],
  defensiveAlternative: 'Verhoog cash/obligatie-allocatie naar 20%. Verschuif naar dividend-ETFs (VIG). Wacht tot VIX onder 20 daalt.',
  offensiveAlternative: 'Vergroot NVDA en QQQ posities agressief bij bullish CPI-reactie. Bitcoin allocatie verhogen naar 15%.',
  doNothingLogic: 'Als CPI morgen tegenvalt en VIX boven 25 uitkomt — wacht met nieuwe aankopen tot volgende week. Geen verplichte actie deze maand.',
  lastUpdated: MINUS_15M,
  dataStatus: 'mock',
  confidenceLevel: 6.8,
  timeHorizon: 'lange-termijn',
};

export const dailyAdvice: AdviceBlock = {
  title: 'Advies voor vandaag',
  subtitle: 'Daghandel — huidige sessie',
  summary:
    'Verhoogde volatiliteit (VIX 24) vraagt discipline. NVDA post-earnings setup is de duidelijkste kans, maar bevestiging vereist. QQQ oversold bounce mogelijk maar Fed-risico aanwezig. Bitcoin test kritieke steunzone. Vermijd shorting voor CPI-data. Beperk posities bij onduidelijkheid.',
  mainDrivers: [
    'NVDA post-earnings momentum — sterkste setup van vandaag',
    'VIX 24 — hoger risico, snellere bewegingen',
    'CPI-data morgen — marktbewegende event',
    'Bitcoin steunzone €60k–€62k wordt getest',
    'Nasdaq oversold op korte termijn',
  ],
  risks: [
    'CPI-data morgen maakt posities vanavond risicovol',
    'VIX boven 22 = bredere spreads en slippage',
    'Geen duidelijk marktdirection voor vandaag',
    'Bitcoin ETF-uitstroom creëert tegenwind',
  ],
  counterArguments: [
    'Oversolde condities maken bounces mogelijk',
    'NVDA earnings-reactie is bullish katalysator',
    'Marktstructuur noch kapitulatie noch doorbraak omhoog',
  ],
  scenarios: {
    bullish: {
      label: 'Bullish intraday',
      description: 'NVDA bevestigt boven €804, Nasdaq volgt.',
      probability: 'gemiddeld',
      implication: 'NVDA naar €841–€860. QQQ naar €453. Bitcoin houdt €62k.',
      watchTriggers: ['NVDA >€806 op hoog volume', 'VIX onder 22', 'Nasdaq groen open'],
    },
    bearish: {
      label: 'Bearish intraday',
      description: 'Zwakke open, NVDA falend, Bitcoin doorbrekend.',
      probability: 'gemiddeld',
      implication: 'NVDA test €790. Nasdaq -1,5%. Bitcoin riskeert €60k.',
      watchTriggers: ['NVDA onder €799', 'VIX >26', 'Bitcoin onder €62k'],
    },
    neutral: {
      label: 'Zijwaarts intraday',
      description: 'Consolidatie voor CPI-data morgen.',
      probability: 'hoog',
      implication: 'Weinig duidelijke setups. Observeren, geen forceren.',
      watchTriggers: ['SPX tussen €4.900–€4.950', 'Laag volume middag'],
    },
  },
  conclusion:
    'NVDA is de enige setup met voldoende ratio. QQQ als risicobeheer. Bitcoin voor geavanceerde traders bij steunbevestiging. Voor de meesten geldt: kleine positiegrootte of wachten op CPI-data.',
  actionPoints: [
    'NVDA-setup bij open monitoren — entry alleen bij bevestiging boven €806',
    'Positiegrootte 50% van normaal vanwege VIX >22',
    'Stop-loss strak handhaven — geen ruimte voor grote drawdowns',
    'Geen nieuwe setups na 15:00 NL-tijd (voor CPI-data)',
    'Bitcoin: wacht op reversal-signaal voor entry',
  ],
  whatToAvoid: [
    'Shorting SPY voor CPI-data',
    'Grote posities in volatiele markt',
    'Averaging down bij verliezende posities',
    'Handelen na 16:00 NL zonder duidelijke reden',
  ],
  defensiveAlternative: 'Geen posities vandaag. Observeren. Bereid zijn voor morgen na CPI-data.',
  offensiveAlternative: 'Volle NVDA setup bij sterke open. QQQ long als Nasdaq groen opent. Bitcoin bij €61.000 met enge stop.',
  doNothingLogic: 'Als de open zwak is en NVDA onder €799 opent — vandaag niet handelen. CPI-data afwachten. Dit is een geldige keuze.',
  lastUpdated: MINUS_15M,
  dataStatus: 'mock',
  confidenceLevel: 6.2,
  timeHorizon: 'intraday',
};

export const eveningAdvice: AdviceBlock = {
  title: 'Advies voor morgen',
  subtitle: 'Avondbriefing — voorbereiding volgende sessie',
  summary:
    'CPI-data morgenochtend 14:30 is het centrale event. Dit bepaalt de marktrichting voor de rest van de week. Bullish CPI-verrassing opent kansen. Bearish verrassing verhoogt correctierisico. NVDA-levels en Bitcoin-steunzone zijn de twee instrumentele focuspunten. Bereid twee scenario\'s voor: actief handelen bij meevallende data, defensief bij tegenvallende data.',
  mainDrivers: [
    'CPI-data 14:30 — marktbepalend event',
    'NVDA post-earnings: €790 steun vs €860 target',
    'Bitcoin steunzone integriteit €60k–€62k',
    'VIX-niveau bepaalt handelskwaliteit',
    'Fed-communicatie voor/na CPI',
  ],
  risks: [
    'CPI hoger dan 3,2% — significante sell-off mogelijk',
    'Bitcoin doorbrekend onder €60k',
    'Geopolitieke verrassing overnight',
    'Hogere open op basis van verwachting — reversal-risico',
  ],
  counterArguments: [
    'Markt al deels ingeprijsd op negatief scenario',
    'NVDA fundamentals sterk — koopkans bij correctie',
    'LTH Bitcoin verkoopt niet — structureel intact',
  ],
  scenarios: {
    bullish: {
      label: 'CPI valt mee (<2,9%)',
      description: 'Inflatie daalt naar of onder consensus.',
      probability: 'gemiddeld',
      implication: 'Nasdaq +2–3%. NVDA naar €841+. Bitcoin boven €65k. Full deployment gerechtvaardigd.',
      watchTriggers: ['CPI <2,9%', 'VIX onder 20 na data', 'Tech futures groen pre-market'],
      invalidation: 'Ongeldig bij CPI > 3,0%',
    },
    bearish: {
      label: 'CPI valt tegen (>3,2%)',
      description: 'Inflatie stijgt of stagneert boven verwachting.',
      probability: 'gemiddeld',
      implication: 'SPX test €4.700. Nasdaq -3–5%. Bitcoin test €57k–€60k. Defensief blijven.',
      watchTriggers: ['CPI >3,2%', 'VIX >26', 'Treasury yields stijgen >10bp'],
      invalidation: 'Ongeldig bij CPI < 3,0%',
    },
    neutral: {
      label: 'CPI in lijn (2,9–3,0%)',
      description: 'Data in lijn met consensus.',
      probability: 'hoog',
      implication: 'Markt gedeeltelijk opgelucht. Volatiliteit daalt. Selectieve kansen in sterke namen.',
      watchTriggers: ['CPI tussen 2,9%–3,1%', 'Marktreactie beperkt'],
    },
  },
  conclusion:
    'CPI is het enige wat morgen echt telt. Bereid beide scenario\'s voor. Stel price alerts in voor SPX €5.000, NVDA €790/€860, Bitcoin €60k/€65k. Handel pas na initiële marktreactie op CPI-data (± 15 minuten na publicatie).',
  actionPoints: [
    'Alarm instellen voor 14:15 (15 min voor CPI)',
    'Price alert: NVDA €790 (steun), €860 (target)',
    'Price alert: Bitcoin €58.500 (kritiek), €65.000 (target)',
    'Price alert: SPX €5.000 (steun)',
    'Klaar zijn voor scenario A (meevallend) en scenario B (tegenvallend)',
    'Geen posities overnight nemen voor CPI',
  ],
  whatToAvoid: [
    'Grote overnight posities voor CPI',
    'Snel in en uit gaan op eerste CPI-reactie',
    'Bitcoin bijkopen voor €60k-steun getest is',
  ],
  defensiveAlternative: 'Alles in cash. CPI afwachten. Handelen alleen bij bullish verrassing.',
  offensiveAlternative: 'Kleine long-posities in NVDA en QQQ overnight met enge stops. Bitcoin bij €61.000 als hedge.',
  doNothingLogic: 'Als CPI tegenvalt en VIX >26 uitkomt — vandaag niet handelen. Volgende week weer beoordelen.',
  lastUpdated: NOW,
  dataStatus: 'mock',
  confidenceLevel: 7.1,
  timeHorizon: 'volgende-sessie',
};

// ─── Bitcoin Market ───────────────────────────────────────────────────────────

export const bitcoinMarket: BitcoinMarket = {
  currentPrice: 62696,
  currency: 'EUR',
  changePercent24h: -1.87,
  changePercent7d: -6.4,
  dominance: 56.2,
  fearGreedIndex: 42,
  fearGreedLabel: 'Angst',
  keyLevels: {
    support1: '€60.000–€61.500',
    support2: '€55.000–€57.000',
    resistance1: '€65.000–€67.000',
    resistance2: '€70.000–€73.000',
  },
  signals: [
    {
      id: 'btc-sig-1',
      label: 'LTH HODL Wave',
      value: 'Stabiel (75,8%)',
      interpretation: 'Lange-termijn houders verkopen niet — structureel bullish signaal',
      sentiment: 'bullish',
      importance: 'hoog',
    },
    {
      id: 'btc-sig-2',
      label: 'ETF-stromen (7d)',
      value: '-€819 miljoen',
      interpretation: 'Institutionele uitstroom afgenomen maar negatief — korte-termijn druk blijft',
      sentiment: 'bearish',
      importance: 'hoog',
    },
    {
      id: 'btc-sig-3',
      label: 'Fear & Greed Index',
      value: '42 — Angst',
      interpretation: 'Angst-niveau historisch geassocieerd met bodem-vorming op middellange termijn',
      sentiment: 'neutraal',
      importance: 'gemiddeld',
    },
    {
      id: 'btc-sig-4',
      label: 'Bitcoin Dominance',
      value: '56,2%',
      interpretation: 'Hoge dominance wijst op voorkeur voor Bitcoin boven altcoins — kwaliteitssignaal',
      sentiment: 'bullish',
      importance: 'gemiddeld',
    },
    {
      id: 'btc-sig-5',
      label: 'STH Realized Price',
      value: '~€61.000',
      interpretation: 'Short-term holders zitten dicht bij break-even — kritieke steunzone',
      sentiment: 'neutraal',
      importance: 'hoog',
    },
  ],
  dataStatus: 'vertraagd',
  lastUpdated: MINUS_15M,
};

// ─── Evening Brief Items ──────────────────────────────────────────────────────

export const eveningBriefItems: EveningBriefItem[] = [
  {
    category: 'macro',
    title: 'CPI-data morgen 14:30',
    todayObservation: 'Fed-functionaris herhaalt voorzichtige toon. VIX stijgt naar 24. Markt prijst lagere kans op renteverlaging in.',
    tomorrowImplication: 'CPI bepaalt marktrichting voor de rest van de week. Bij meevallende data: relief rally. Bij tegenvallende data: verdere correctie.',
    keyLevelsToCheck: ['SPX €5.000 steun', 'SPX €5.250 weerstand', '10-jaars Treasury yield (>4,5% bearish)'],
    eventRisk: 'CPI-release 14:30 NL-tijd — hoogste impact',
  },
  {
    category: 'aandeel',
    title: 'NVDA post-earnings dynamic',
    todayObservation: 'Sterke earnings. Pre-market +4%. Datacenter-guidance verhoogd. Volume 2,3x gemiddelde.',
    tomorrowImplication: 'Setup voor verdere stijging als boven €806 blijft. Weerstand bij €841–€860.',
    keyLevelsToCheck: ['NVDA €790 steun', 'NVDA €806 bevestigingsniveau', 'NVDA €860 eerste target'],
  },
  {
    category: 'etf',
    title: 'QQQ herstelkans vanuit oversold',
    todayObservation: 'Nasdaq -0,7% vandaag. RSI daags <35. Sentiment negatief maar geen paniek.',
    tomorrowImplication: 'Bij meevallende CPI: oversold bounce mogelijk naar €443–€451. Bij tegenvallende CPI: test €419.',
    keyLevelsToCheck: ['QQQ €419 steun', 'QQQ €432 weerstand', 'QQQ €443 bounce-target'],
  },
  {
    category: 'bitcoin',
    title: 'Bitcoin steunzone integriteit',
    todayObservation: 'Bitcoin -1,9% naar €62.700. ETF-uitstroom €819M (7d). LTH houdt positie.',
    tomorrowImplication: 'Steunzone €60k–€62k kritiek. Bounce kansrijk vanuit deze zone, maar uitstroom is tegenwind.',
    keyLevelsToCheck: ['BTC €60.000 kritieke steun', 'BTC €61.500 herstelbevestiging', 'BTC €67.000 eerste doel'],
    eventRisk: 'ETF-stroomdata morgenochtend (pre-market)',
  },
];

// ─── Daily Summary ────────────────────────────────────────────────────────────

export const dailySummary: DailySummary = {
  date: 'vrijdag 13 maart 2026',
  adviceTitle: 'Selectief handelen — NVDA setup is kans, rest afwachten',
  marketQuality: 'matig',
  topOpportunity: 'NVDA post-earnings long setup bij bevestiging boven €806',
  topRisk: 'CPI-data morgen — marktbepalend event, overnight posities vermijden',
  noTradeCondition: 'Als open zwak is en NVDA onder €799 opent — vandaag niet handelen',
  disciplineNote: 'VIX 24 betekent grotere koersuitslagen. Positiegrootte halveren. Stop-loss strikter handhaven dan normaal. Één goede setup is genoeg.',
  sessionStatus: 'open',
  lastUpdated: MINUS_15M,
};
